### ISSUE TITLE
Gyro Z rotation returns 90d+ after test

### ISSUE THREAD

**Issue by aiden-powers** [FRC-Sonic-Squirrels/MiniBot2023#3]

**Comment by randomstring** [comment]
You need to be more specific. What branch of the code are you referring to. And what test? Is this the gyro testing you did with Davide on Saturday?

**Comment by aiden-powers** [comment]
twas solved by using quaternions

**Comment by randomstring** [comment]
@Powersaj-Tech please comment here what you learned from your experiments with the gyro.

**Comment by aiden-powers** [comment]
Using the Pigeon 2 with the traditional output of Euler Angles, if you tested the gyro and then bring it back to its original position, the Z axis would output +90 degrees, even though it should report 0, because we brought it back to its original orientation.

The way to fix this in my opinion, is to use the more complicated output option, Quaternions. These output a 4 dimensional figure, but fix the issue with the Z rotation supposedly locking up or not compensating for specific rotations.

The branch GyroTest includes a function "getEulerFromQuaternion6d", like the name, it contains the math to convert this figure into what we use for directions.

Another issue presented with this solution though is the lack of resetting the gyro, but it can be fixed if you make an offset on initialization.
